name: Treino de lint

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demonstracao:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensagem
        shell: bash
        run: |
          mensagem="Teste do home-lab"
          echo $mensagem
